PANDA

In [ ]:
import pandas as pd

file_ = pd.read_csv('/content/student_data (2).csv', sep=',')

print(file_.tail())

      study_hours  attendance  sleep_hours  internet_usage  \
9995            2          58            9               7
9996            7          98            6               9
9997           10          44            8               5
9998           10          75            7               5
9999            2          70            6              11

      assignments_completed  previous_score  exam_score placement_status
9995                      8              88       69.31       Not Placed
9996                      4              87      100.00           Placed
9997                     10              37       95.94           Placed
9998                      8              52       88.61           Placed
9999                     16              52       78.96           Placed

In [9]:
# import pandas as pd
# dct={
#     'name':['sgaar','kunu','goutuam','harshit'],
#     'age':[20,21,19,10],
#     'roll':[1,2,3,4,]
# }

# df=pd.DataFrame(dct)
# df1=pd.DataFrame(dct,)
# display(df)
# display(df1)

      name  age  roll
0    sgaar   20     1
1     kunu   21     2
2  goutuam   19     3
3  harshit   10     4

      name  age  roll
0    sgaar   20     1
1     kunu   21     2
2  goutuam   19     3
3  harshit   10     4

In [18]:
df=pd.read_csv("/content/student_data (2).csv")
# df.head(3)
# print("\n")
df.head(3)


df.tail()
df.shape

df.info
df.describe()

,study_hours,attendance,sleep_hours,internet_usage,assignments_completed,previous_score,exam_score
count,10000.000000,10000.00000,10000.000000,10000.000000,10000.000000,10000.00000,10000.000000
mean,5.989600,69.88460,6.498500,6.062600,9.988400,64.91100,86.704207
std,3.163589,17.61653,1.709354,3.138163,6.034145,17.50302,15.058383
min,1.000000,40.00000,4.000000,1.000000,0.000000,35.00000,26.670000
25%,3.000000,55.00000,5.000000,3.000000,5.000000,50.00000,76.727500
50%,6.000000,70.00000,6.500000,6.000000,10.000000,65.00000,92.120000
75%,9.000000,85.00000,8.000000,9.000000,15.000000,80.00000,100.000000
max,11.000000,100.00000,9.000000,11.000000,20.000000,95.00000,100.000000

In [50]:
df=pd.read_csv("/content/student_data (2).csv")
# df.tail(3)

# df.index
# df[['study_hours','internet_usage']]

# df.study_hours

# df.iloc[0,5]  #access the row

# df.loc[df['study_hours']==11,['study_hours','sleep_hours']]

# df2=df.loc[df['study_hours']==11]
# df2[['study_hours','sleep_hours']]

# df.loc[4]

#loc works on label
# iloc works on index


df.loc[df["assignments_completed"] == 8].iloc[1]

study_hours                   5
attendance                   52
sleep_hours                   8
internet_usage                6
assignments_completed         8
previous_score               40
exam_score                78.82
placement_status         Placed
Name: 4, dtype: object

In [72]:
df=pd.read_csv("/content/student_data (2).csv")
# df[df['assignments_completed']>3]

# df["age"]=28
# df

# Reaname column
# df.rename(columns={'assignments_completed':'assign_completed'}, inplace=True)
# df

# df.drop('assignments_completed',axis=1,inplace=True)
# df
df.drop(0,axis=0,inplace=True)
df

,study_hours,attendance,sleep_hours,internet_usage,assignments_completed,previous_score,exam_score,placement_status
1,4,69,5,3,8,56,100.00,Placed
2,11,60,7,6,10,45,100.00,Placed
3,8,99,9,8,4,55,90.17,Placed
4,5,52,8,6,8,40,78.82,Placed
5,7,40,9,10,0,60,72.33,Placed
...,...,...,...,...,...,...,...,...
9995,2,58,9,7,8,88,69.31,Not Placed
9996,7,98,6,9,4,87,100.00,Placed
9997,10,44,8,5,10,37,95.94,Placed
9998,10,75,7,5,8,52,88.61,Placed
9999,2,70,6,11,16,52,78.96,Placed

In [98]:
dic={
    'name':['kunu','goutuam','harshit','sagar'],
    'age':[20,21,19,10],
    'roll':[1,2,3,4,]

}

df=pd.DataFrame(dic)
# df1=pd.DataFrame(dct,)
display(df)
# display(df1)
df.drop('age',axis=1,inplace=True)
df

df.dropna(axis=1,inplace=True)
df

df.filter(1,inplace=True)
df

      name  age  roll
0     kunu   20     1
1  goutuam   21     2
2  harshit   19     3
3    sagar   10     4

TypeError: NDFrame.filter() got an unexpected keyword argument 'inplace'